# Generated by Django 3.2.6 on 2021-08-08 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='timeout',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='run',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='status',
            field=models.TextField(default='sucess'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problem',
            name='setter',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='run',
            name='user_id',
            field=models.TextField(),
        ),
    ]
