version: '3.7'
services:
  mongo:
    image: mongo:3.4.2
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - '27017:27017'
    command: mongod --auth
    networks: 
      - net
  rabbitmq:
    image: 'rabbitmq:3-management-alpine'
    container_name: rabbitmq
    restart: always
    volumes:
      - '/docker/rabbitmq/data:/var/lib/rabbitmq'
    ports:
      - '5672:5672'
      - '15672:15672'
    networks: 
      - net
  users:
    build:
      context: ./
      dockerfile: users.dockerfile
      args:
        prod: prod
    container_name: users
    restart: always
    ports:
      - '8001:8000'
    depends_on:
      - "mongo"
    networks: 
      - net
  problems:
    build:
      context: ./
      dockerfile: problems.dockerfile
      args:
        prod: prod
    container_name: problems
    restart: always
    depends_on:
      - "mongo"
      - "rabbitmq"
    ports:
      - '8002:8000'
    networks: 
      - net
  scores:
    build:
      context: ./
      dockerfile: scores.dockerfile
      args:
        prod: prod
    container_name: scores
    restart: always
    depends_on:
      - "mongo"
      - "rabbitmq"
    ports:
      - '8003:8000'
    networks: 
      - net
  runner:
    build:
      context: ./
      dockerfile: runner.dockerfile
    container_name: runner
    restart: always
    depends_on:
      - "rabbitmq"
    ports:
      - '8004:8080'
    networks: 
      - net
networks:
  net:
    name: onlinejudge